# Generated by Django 5.0.2 on 2024-03-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomJWT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AJIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=64)),
                ('Price', models.FloatField()),
                ('MRP', models.FloatField()),
                ('Discount', models.FloatField()),
                ('URL', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
