# Generated by Django 5.0.2 on 2024-03-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomJWT', '0003_alter_ajio_discount_alter_ajio_mrp_alter_ajio_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajio',
            name='URL',
            field=models.CharField(max_length=100),
        ),
    ]
