# Generated by Django 5.0.2 on 2024-03-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomJWT', '0004_alter_ajio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajio',
            name='Discount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ajio',
            name='MRP',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ajio',
            name='Price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ajio',
            name='ProductName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ajio',
            name='URL',
            field=models.CharField(max_length=255),
        ),
    ]
